name: Test target-clickhouse

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Install Poetry
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Run lint command from tox.ini
      run: |
        poetry run tox -e lint

  pytest:
    runs-on: ubuntu-latest
    services:
      clickhouse-server:
        image: clickhouse/clickhouse-server:23.4-alpine
        ports:
          - 18123:8123
          - 19000:9000
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'
    - name: Install Poetry
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest \
          --capture=no \
          --deselect=tests/test_core.py::TestTargetClickhouse::test_target_camelcase \
          --deselect=tests/test_core.py::TestTargetClickhouse::test_target_camelcase_complex_schema

  integration:
    runs-on: ubuntu-latest
    services:
      clickhouse-server:
        image: clickhouse/clickhouse-server:23.4-alpine
        ports:
          - 18123:8123
          - 19000:9000
    env:
      python-version: "3.8"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pipx install meltano
        meltano install
    - name: smoke-test-tap
      run: meltano run tap-smoke-test target-clickhouse
